server:
  port: ${SERVER_PORT:8081}

spring:
  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost:9411/}
    enabled: true
  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_SERVER_URL:http://localhost:8085} #admin server port

eureka:
  client:
    instance:
      hostname: ${EUREKA_SERVER_HOST:localhost}
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

accountservice: 
  cassandra:
    contact:
      point: ${CASSANDRA_SERVER_HOST:localhost}
    port: ${CASSANDRA_SERVER_PORT:9042}
    username: ${CASSANDRA_SERVER_USERNAME:cassandra}
    password: ${CASSANDRA_SERVER_PASSWORD:cassandra}
    keyspace:
      name: ${CASSANDRA_SERVER_KEYSPACE:ticketsystem}

management: #production ortamında buna dıkkat etmek lazım
  endpoints:
    web:
      exposure:
        include: "*"