server:
  port: 8081

spring:
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
  boot:
    admin:
      client:
        url: http://localhost:8085 #admin server port

eureka:
  client:
    instance:
      hostname: ${EUREKA_SERVER_HOST:localhost}
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

accountservice: 
  cassandra:
    contact:
      point: localhost
    port: 9042
    username: cassandra
    password: cassandra
    keyspace:
      name: ticketsystem

management: #production ortamında buna dıkkat etmek lazım
  endpoints:
    web:
      exposure:
        include: "*"