server:
  port: 8083

spring:
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
  boot:
    admin:
      client:
        url: http://localhost:8084 #admin server port

eureka:
  client:
    instance:
      hostname: ${EUREKA_SERVER_HOST:localhost}
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

#RabbitMQ için konfigürasyon ayarları.
spring:
  rabbitmq:
    username: eokumus
    password: eokumus
    host: localhost
    port: 5672
  cloud:
    stream:
      bindings:
        input:  #kuyruğu dinleyen
          destination: ticketnotificationqueue

management: #production ortamında buna dıkkat etmek lazım
  endpoints:
    web:
      exposure:
        include: "*"

