server:
  port: ${SERVER_PORT:8082}

eureka:
  client:
    instance:
      hostname: ${EUREKA_SERVER_HOST:localhost}
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3307/ticketsystem}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:ticketsystem}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  rabbitmq:
    username: ${RABBİTMQ_USERNAME:eokumus}
    password: ${RABBİTMQ_PASSWORD:eokumus}
    host: localhost
    port: 5672
  cloud:
    stream:
      bindings:
        output: #kuyruğa publish edecek olan
          destination: ticketnotificationqueue
  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost:9411/}
    enabled: true
  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_SERVER_URL:http://localhost:8085} #admin server port

management: #production ortamında buna dıkkat etmek lazım
  endpoints:
    web:
      exposure:
        include: "*"