server:
  port: 8082

eureka:
  client:
    instance:
      hostname: ${EUREKA_SERVER_HOST:localhost}
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3307/ticketsystem}
    username: ${MYSQL_URL:root}
    password: ${MYSQL_URL:ticketsystem}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  rabbitmq:
    username: eokumus
    password: eokumus
    host: localhost
    port: 5672
  cloud:
    stream:
      bindings:
        output: #kuyruğa publish edecek olan
          destination: ticketnotificationqueue
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
  boot:
    admin:
      client:
        url: http://localhost:8084 #admin server port

management: #production ortamında buna dıkkat etmek lazım
  endpoints:
    web:
      exposure:
        include: "*"